### ISSUE TITLE
Add a way to inspect containers created

### ISSUE THREAD

**Issue by khaledkbadr** [g8os/core0#103]
Add inspect container functionality to show 
- Exposed ports mapping
- Exposed volumes mapping
- Exposed bridges used

**Comment by grimpy** [comment]
@khaledkbadr which kind of inspection you need? Please update the description

**Comment by khaledkbadr** [comment]
@grimpy Added description needed for me. Feel free to add any inspection you need in the description

**Comment by zaibon** [comment]
It would be convenient to be able to read all the info we pass during the creation so :
- root_url
- mount,
- host_network
- zerotier
- bridge
- port
- hostname
- storage
