### ISSUE TITLE
Btrfs extension needs extra features

### ISSUE THREAD

**Issue by grimpy** [g8os/core0#104]
* make it possible to create a snapshots of a subvolum
** Input params srcpath destpath readonly=False

* add quota support on subvolumes see: https://btrfs.wiki.kernel.org/index.php/Quota_support

**Comment by muhamadazmy** [comment]
- I have merged the snapshot feature
- quote mgmt was delayed because of low  prio

**Comment by john-kheir** [comment]
## Verified on 1.1.0-alpha
