### ISSUE TITLE
Can't create btrfs file system

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#113]
In [65]: client.btrfs.create('main2btrfs', ['/dev/loop3','/dev/loop4'], metadata_profile='raid1', data_profile='raid1')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-65-53f94ae36b38> in <module>()
----> 1 client.btrfs.create('main2btrfs', ['/dev/loop3','/dev/loop4'], metadata_profile='raid1', data_profile='raid1')

/usr/local/lib/python3.5/dist-packages/g8core/client.py in create(self, label, devices, metadata_profile, data_profile)
    954 
    955         if result.state != 'SUCCESS':
--> 956             raise RuntimeError('failed to create btrfs FS %s' % result.data)
    957 
    958     def device_add(self, mountpoint, *device):

RuntimeError: failed to create btrfs FS "error creating btrfs filesystem: [btrfs-progs v4.8\nSee http://btrfs.wiki.kernel.org for more information.\n ERROR: failed to check size for /dev/loop3 /dev/loop4: No such file or directory\n]"

**Comment by zaibon** [comment]
fixed in #114
