### ISSUE TITLE
When container is terminated, 'df -h' throw stderr

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#120]
## This need to be investigated in the last version
![photo_2017-04-04_13-19-10](https://cloud.githubusercontent.com/assets/15011431/24654323/71e78982-1939-11e7-94bb-6dffd9591ca5.jpg)

**Comment by zaibon** [comment]
no need to shout ;-)

**Comment by mie00** [comment]
Couldn't reproduce on Version 1.1.0-alpha.

**Comment by john-kheir** [comment]
## Verified on 1.1.0-alpha
