### ISSUE TITLE
failed to create container

### ISSUE THREAD

**Issue by yveskerwyn** [g8os/core0#121]
I first started a Docker container with Core0:

```
docker run --privileged -d --name core -p 6379:6379 g8os/g8os-dev:1.0
```

then using js:
```
cl = j.clients.g8core.get("172.17.0.2")

flist = "https://hub.gig.tech/maxux/ubuntu1604.flist"
container_id = cl.container.create(flist, storage='ardb://hub.gig.tech:16379', host_network=True)
```

=> RuntimeError:
```
failed to create container "mount-root-plist(upnormal exit of filesystem mount at '/mnt/container-8')"
```

**Comment by muhamadazmy** [comment]
Yeah, the docker image is not uptodate. I strongly suggest that u use the initramfs image from https://github.com/g8os/initramfs

**Comment by zaibon** [comment]
How come it's not up to date? That's 1.0,  it should work for that release. Please make sure the docker image is usable
