### ISSUE TITLE
bridge hardwareaddr value is not equal to the assigned value

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/core0#127]
### Steps
- Create new bridge and set its MAC address
- Get network interfaces and check the mac address (hardwareaddr) of the created bridge

```bash
c.bridge.create('test', hwaddr='ab:13:2d:f5:6e:25')
``` 
from ``` c.info.nic() ```
```bash
{'addrs': [{'addr': 'fe80::c031:5ff:feca:a3f7/64'}],
  'flags': ['up', 'broadcast', 'multicast'],
  'hardwareaddr': 'c2:31:05:ca:a3:f7' ,
  'mtu': 1500,
  'name': 'test'}
```

### Actual result
hardwareaddr value is not equal to the assigned value

**Comment by john-kheir** [comment]
use fake  hwaddr='ab:13:2d:f5:6e:26'
```In [9]: client.bridge.create('test3', hwaddr='ab:13:2d:f5:6e:26')
---------------------------------------------------------------------------
RuntimeError: failed to create bridge "cannot assign requested address"
```
It's okay with the runtime error but  the bridge test3 shouldn't be listed then

client.info.nic()
```{'addrs': [],
  'flags': ['broadcast', 'multicast'],
  'hardwareaddr': '32:64:7d:0b:c7:b0',
  'mtu': 1500,
  'name': 'test3'},
```

**Comment by mie00** [comment]
@muhamadazmy should we remove the nic in case that it didn't get the requested (invalid) address?

**Comment by john-kheir** [comment]
## Verified on 1.1
