### ISSUE TITLE
Support OVS networking mode for containers and vms

### ISSUE THREAD

**Issue by muhamadazmy** [g8os/core0#131]
# Goal
- [x] Drop default networking (or make a flag to enable/disable it)
- [x] Allow other networking settings that requires (ovs plugin) to connect a container over vxland and/or vlan.

## Notes
I think we should totally drop default networking for the following reason:
- No production use case.
- To much code to maintain (default networking over linux bridges - dnsmasq, socat for port forwarding)
- A container should be only created with 3 networking modes:
  - No neworking at all
  - Host Networking 
  - OVS networking (vxlan, and or vlan)
- To create a container with a OVS networking your host must have an OVS container running (to provide the ovs networking plugin)

**Comment by john-kheir** [comment]
Verified on Version: 1.1.0-alpha @Revision: d1b3e6658c6805786abe795a080745c4aba39f0c
