### ISSUE TITLE
can't write to file opened in append and w+ modes

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/core0#133]
### Steps 
- Create text file and open it in append mode (a)
- try to write to it

- close the file and open it in w+ mode
- try to write to it

### Actual result
![image](https://cloud.githubusercontent.com/assets/24386820/24715833/39583ef0-1a2d-11e7-9422-5005810c110a.png)

![image](https://cloud.githubusercontent.com/assets/24386820/24747514/e47e551e-1abc-11e7-89e2-1d7790cb4f2f.png)

**Comment by mie00** [comment]
The problem is that a file has to be opened using one and only one of those parameters:
RDWR, RDONLY, WRONLY
and in append none of those are used.
I think this can be a good reference to implement the open method
https://github.com/python-git/python/blob/py3k/Modules/_fileio.c#L226

**Comment by john-kheir** [comment]
## Verified on 1.1.0-alpha
