### ISSUE TITLE
the dns of the g8os host is changed after creating bridge with network dnsmasq

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/core0#147]
### Steps
- check the dns of the g8os host  ``` cat /etc/resolv.conf```
- create bridge with network **dnsmasq**
- create container and attach the create bridge to it
- check the dns of the g8os host again

### Actual result
the dns is changed to the ip of the created bridge 

steps (left), results(right)

![image](https://cloud.githubusercontent.com/assets/24386820/24860689/1a99f86a-1df6-11e7-9a5c-5e0185b7416e.png)

**Comment by john-kheir** [comment]
## Verified on 1.1
