### ISSUE TITLE
Create partition with "extended" type with table type "gpt" 

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/core0#149]
### Steps
- create table for disk with type='gpt' -> disk.mktable(disk_name) #as default type gpt 
- create partition with type extended -> disk.mkpart(diskname,start,end,'extended') 

### Expected Result 

Error as should not  create extended partition with "gpt"  table type ,should use 'msdos' type

### Actual Result 
Partition created  with no problem

**Comment by khaledkbadr** [comment]
It's not a problem. Parted allow extended partitions with gpt label
