### ISSUE TITLE
bridge.delete doesn't cleanup the firewall rules

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/core0#153]
### Steps
-  Create bridge **B1** and let **NAT=True**
-  Create container and attach bridge **B1** to it
-  Using container client remove the default network interface **eth0** 
-  Set network interface **eth1** as a  default route
-  try to ping 8.8.8.8, should succeed 
- Delete bridge **B1**

-  repeat all the above steps again  with **NAT=False** 
  (keep bridge name and cidr the same)

### Actual result 
- container can reach 8.8.8.8, when NAT=False

**Comment by john-kheir** [comment]
Verified on Version: 1.1.0-alpha @Revision: d1b3e6658c6805786abe795a080745c4aba39f0c
