### ISSUE TITLE
Can't access this machine

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#169]
This issue happened more than one time
I can't access the machine using the python client nor the telnet 
Please try to debug this machine as soon as possible
**ip: 147.75.100.25**
Note: the machine is there on packet
![111111](https://cloud.githubusercontent.com/assets/15011431/25131486/3a98260e-2446-11e7-871f-9143fd042b11.png)

**Comment by muhamadazmy** [comment]
I can't manage to get the `console` output of this machine so i can not tell what killed it. @maxux Can u find a way to make the console works in packet.net ?

**Comment by maxux** [comment]
Please use extra bootstrap option: `/console=ttyS1,115200n8`

For exemple, use this iPXE script: `https://bootstrap.gig.tech/ipxe/1.1.0-alpha/abcdef/console=ttyS1,115200n8`

**Comment by muhamadazmy** [comment]
@john-kheir Make sure that u start all the machines with the correct iPXE url so we have enough debug info in console.

Reopen if u can reproduce and u have console logs.
