### ISSUE TITLE
G8os crash after creating first container

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#189]
nic = [{'type': 'zerotier', 'id': networkId}]
cid_1 = self.create_container(root_url=self.root_url, storage=self.storage, nics=nic)

![errrrrr](https://cloud.githubusercontent.com/assets/15011431/25433248/fb7e647c-2a87-11e7-89b4-f95fae4b1de6.png)

**Comment by muhamadazmy** [comment]
Fixed

**Comment by john-kheir** [comment]
The g8os doesn't crash anymore but the container doesn't take zt_ip when created

**Comment by john-kheir** [comment]
now id does take ip
