### ISSUE TITLE
Can not install js on g8os

### ISSUE THREAD

**Issue by ashraffouda** [g8os/core0#190]
I tried to install js on a container and it always fails at this line https://github.com/Jumpscale/jumpscale_core8/blob/8.2.0/install/install.sh#L98
the error was something like this 
```
+ apt-get install mc curl git ssh python3.5 -y
E: Package 'mc' has no installation candidate
```

I added extra sources to sources.list then the error changed to 
```
Errors were encountered while processing:
 libssh2-1:amd64
```
where `apt-get install -f` and `dpkg --configure -a` can not help

**Comment by muhamadazmy** [comment]
This was working before, we need to retest it.

**Comment by mie00** [comment]
I changed apt sources to my local sources, the default of a normal desktop ubuntu installation and all the packages was installed without a problem.
