### ISSUE TITLE
Add an api to get/set config from g8os.conf

### ISSUE THREAD

**Issue by grimpy** [g8os/core0#197]
Currently its not possible withouth client.filsystem.download to read config.
It would be nice to have an api to read the config.
Where possible it would be nice to be able to change config at runtime

**Comment by mie00** [comment]
config get implemented https://github.com/g8os/core0/commit/8d52296779b4d59ef50e20e4ef3f330a1a715d1f

**Comment by john-kheir** [comment]
Verified on Version: 1.1.0-alpha @Revision: d1b3e6658c6805786abe795a080745c4aba39f0c
