### ISSUE TITLE
No response when  directory is created 

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#205]
There should be a clear response when a directory is created or when it fails

```
In [46]: rs = client.filesystem.mkdir('test')

In [47]: rs = client.filesystem.mkdir('test')

In [48]: rs = client.filesystem.mkdir('test')
```

**Comment by muhamadazmy** [comment]
As I said, our mkdir `ensures` that the directory exists and if not exist, it will create it (similar to `mkdir -p`)

This makes automation and scripting easier so u don't check if directory exists before u create it.
