### ISSUE TITLE
Btrfs device_remove call never gives an error

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#213]
**client.btrfs.device_remove('/mnt/test', '/dev/loop1') don't give error in any of these cases:**
1- Assuming '/mnt/test' is a fake mount point
2- Assuming '/mnt/test' is a mount point for file system (fs1), in which '/dev/loop1' is a device mounted on another filesytem (fs2) mount point 
3- Assuming that '/dev/loop1' is any fake device

**Note: All of these cases give specific error using 'btrfs' command line**

**Comment by muhamadazmy** [comment]
That was a client issue, it didn't propagate the error. Fixed. To test please make sure u have latest client.

**Comment by john-kheir** [comment]
verified on Version: 1.1.0-alpha-removenic @Revision: e23b1c5051c75f9a7af11f701dc7d6aab1cf0415'
