### ISSUE TITLE
g8core.client() doesn't raise timeout exception 

### ISSUE THREAD

**Issue by islamTaha12** [g8os/core0#215]
g8core.client() doesn't raise timeout exception. I waited arround15 mins and there is no response.

Steps:
Try to connect to a fake ip.

**Comment by john-kheir** [comment]
still the case .. it hangs for a long time
### Version
1.1.0-alpha @Revision: 867d58e68dd938f90f2190c2a48cbf300489f1a0

**Comment by zaibon** [comment]
@john-kheir can you point me to your test regarding this please.
