### ISSUE TITLE
Hot plugging default network is not supported

### ISSUE THREAD

**Issue by khaledkbadr** [g8os/core0#220]
command:  `node.client.kvm.add_nic("1ca35dd3-e2cf-456d-82f0-ee0d8acf6458", "default", "50", "00:16:3e:38:41:47")`

Error:
```
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"default network hot plugging is not supported at the moment"
)
```

**Comment by john-kheir** [comment]
Verified on 1.1.0-alpha @Revision: 867d58e68dd938f90f2190c2a48cbf300489f1a0
