### ISSUE TITLE
Same vdisk can be attached to two different vms

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#222]
Now our g8os system (using kvm) allow us to attach same vdisk to two different vms, however i think this behavior shouldn't be accepted.

### Version
1.1.0-alpha @Revision: cb9127069375fb32a5e03ac88ab71504212487aa

**Comment by mie00** [comment]
This is not an issue for g8os, but it has to be handled in the api or ays, closing and creating an issue there.
https://github.com/g8os/resourcepool/issues/190
