### ISSUE TITLE
G8OS crashed on be-g8-3:cpu-10

### ISSUE THREAD

**Issue by FastGeert** [g8os/core0#230]
![afbeelding](https://cloud.githubusercontent.com/assets/15246294/25986109/7027d6d8-36ee-11e7-99f5-c9fb9efee324.png)

**Comment by grimpy** [comment]
[logs.tar.gz](https://github.com/g8os/core0/files/1000310/logs.tar.gz)

**Comment by grimpy** [comment]
![photo_2017-05-15_09-05-55](https://cloud.githubusercontent.com/assets/143869/26046134/c3cecf56-394d-11e7-831a-69f0f3727933.jpg)

**Comment by grimpy** [comment]
[logs.tar.gz](https://github.com/g8os/core0/files/1000885/logs.tar.gz)
