### ISSUE TITLE
list kvms returns error 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/core0#236]
![image](https://cloud.githubusercontent.com/assets/24386820/26035740/5c3810e0-38d1-11e7-8bdb-4ce3d5bff1d3.png)

**Comment by john-kheir** [comment]
Verified on master @Revision: f3dd77f8dd098b4c93ae77706d84acf488ce4283

**Comment by ahmedelsayed-93** [comment]
new error appears  
![image](https://cloud.githubusercontent.com/assets/24386820/26282816/ef0e78ae-3e18-11e7-8bb2-7d38056fb05a.png)

### SV
master 26d994a

**Comment by john-kheir** [comment]
Verified on master @Revision: 28b1f6f63d0c96085fd2f3edbc6f1f9c557dd040
