### ISSUE TITLE
Wrong doc for create container with nics 

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/core0#247]
## Issue 
![selection_344](https://cloud.githubusercontent.com/assets/24386802/26106063/f46eebda-3a44-11e7-8e73-b2aee03607b0.png)
Configuration should be for bridge too 
## SV 
ac9a0f2859ae14d04975c06fb082495685be6397

**Comment by john-kheir** [comment]
Verified on master @Revision: c74c53d2b1f284d46440a334eff9e8d60d8448d2
