### ISSUE TITLE
Can't connect using g8os client or ssh to g8os nodes 

### ISSUE THREAD

**Issue by john-kheir** [g8os/core0#260]
```
In [7]: client = g8core.Client('147.75.204.165')
RuntimeError: Could not connect to remote host 147.75.204.165

``` 
## image used
g8os-master.efi 
    >>g8os-master-initramfs-76c05b34.efi

**Comment by grimpy** [comment]
Should be fixeed, please verify

**Comment by john-kheir** [comment]
Verified on master @Revision: c1fa6d9f7a8ea399406940a719809602b9e853ee

**Comment by john-kheir** [comment]
This issue is happening again

**Comment by muhamadazmy** [comment]
Fixed

**Comment by john-kheir** [comment]
Verified on master @Revision: c74c53d2b1f284d46440a334eff9e8d60d8448d2
