### ISSUE TITLE
allow to overwrite a partition table with the disk.mktable command

### ISSUE THREAD

**Issue by zaibon** [g8os/core0#62]
Currently, there is no way to create a new partition table if there is already one on the disk.
We should support the overwritting of already existing partition tables.
The client should have overwrite argument that add the `force` option to the `mktable` call.

**Comment by muhamadazmy** [comment]
It's much more trickeier to have a `force` flag. It's more straight forward to run parted in `script` mode by default (non-interactive)

https://github.com/g8os/core0/commit/0c0599249455d7e0e63b3da110edb9a97d37f48d
