### ISSUE TITLE
Client timeouts

### ISSUE THREAD

**Issue by zaibon** [g8os/core0#64]
It happens sometimes that the client timeout even if the ping command respond immediatly.
Which make me think there is a problem in the core0 itself.

Here is the little script that I use to reproduce:
```python
from g8core.client import Client
cl = Client('172.20.0.1')
for i in range(10):
    cl.bash('ls /') 

# this call timeout
cl.disk.list()
```

**Comment by muhamadazmy** [comment]
Fixed
