### ISSUE TITLE
Add a way to choose the fuse_storage address during runtime

### ISSUE THREAD

**Issue by maxux** [g8os/core0#75]
The `fuse_storage` should not be hardcoded on the config.
I see two possibilities:
- [ ] Set a global variable changeable from the client
- [ ] Set a per-container storage address

Both will be the best but at least the first one is really important since we need to rebuild the image if the address is wrong.

**Comment by muhamadazmy** [comment]
https://github.com/g8os/core0/commit/e744bfd84044abf0645d21ea20fae56b92909728
