### ISSUE TITLE
Make it possible to add cdrom to vm

### ISSUE THREAD

**Issue by grimpy** [g8os/core0#87]
For simplicity I would make this 
cl.experimental.kvm.create(name, images, cpu=2, memory=512, port=None, bridge=None, cdrom=None)

**Comment by muhamadazmy** [comment]
Make sure to use new client, since client compatibility is broken with older api (regarding creating KVM domains)

**Comment by robvanmieghem** [comment]
@muhamadazmy Can you add `Fixes #87` or similar comment ( https://help.github.com/articles/closing-issues-via-commit-messages/ ) to the commit in the future? This way it's easier for someone else to see the related changes.

**Comment by muhamadazmy** [comment]
@robvanmieghem sure.
