### ISSUE TITLE
Documentation about toml script to create commands

### ISSUE THREAD

**Issue by zaibon** [g8os/core0#93]
We need documentation about how to use these toml script to create commands:

- [x] : Explain what can be achieve with it. (command, startup, ...)
- [x] : Document the current toml that exists
- [ ] : Small internal documentation how it works

**Comment by muhamadazmy** [comment]
https://github.com/g8os/core0/tree/0.12.0/docs/config

**Comment by muhamadazmy** [comment]
@zaibon i don't get what kind of internal documentation you need. can u check the provided link and tell me if u think we can add more.
